# B.Tech Computer Science and Engineering(Software Engineering)
# Balkrishna Mehta
# 202103103510434
print("Creation of Tuple: ")
Tuple=(1,2,3,(3,3),5)
print("Index of 2 in Tuple: ")
print(Tuple.index(2))
print("Index of 5 in Tuple: ")
print(Tuple.index(5))
print("Repetition of 3 in tupple: ")
print(Tuple.count(3))
print("Repetition of 3 in tupple in index 3 of tuple: ")
print(Tuple[3].count(3))
print("Element at index 1 in Tuple: ")
print(Tuple[1])
print("Element at index -1 in Tuple: ")
print(Tuple[-1])
print("Element Between index 1 an 3 excluding 3 in Tuple: ")
print(Tuple[1:3])
