# B.Tech Computer Science and Engineering(Software Engineering)
# Balkrishna Mehta
# 202103103510434
print("Creation of Dictonary: ")
dict = {"Name" : "Ayush" , "Age" : 18, "Branch" : "B.tech cse(se)"}
print(dict)
dict["Name"] = "Balkrishna Mehta"
print("dict after updating name: ")
print(dict)
dict.update({"Roll no": 38 })
print("adding roll no to the dict: ")
print(dict)
dict.pop("Roll no")
print("deleting key roll no from dict: ")
print(dict)
print("\n")
print("All values from key-value pair of dict:  ",end="")
print(dict.values())       # It will return all value from dictonary  (class = dict_values)
print("Each key-value pair of dict in tuple:  ",end="")
print(dict.items())        # It will return tupple of all key value pair   (class = dict_items)
print("All keys from key-value pair of dict:  ",end="")
print(dict.keys())         # it will return all key from key,value pair i.e return index of dictonary (class = dict_keys)
print("\n")
print("value of key of specified key: ")
print(dict.get("Age"))
print("dict after deleting last key value pair: ")
dict.popitem()
print(dict)
dict1=dict.copy()
print("copied dict1 from dict: ")
print(dict1)
dict1.clear()
print("dict1 after using .clear()")
print(dict1)
